source 'https://github.com/CocoaPods/Specs.git'

target 'ObjcAdPieX' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ObjcAdPieX
  pod 'AdPieX-SDK', '1.0.0'

end
